name: Awesome Low Code PR validation

on: [pull_request]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.35.0
      name: Spellcheck
      with:
        config_path: .pyspelling.yml

  awesomelint:
    name: Awesome Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npx awesome-lint